### ISSUE TITLE
4 * is repeated several times on the same value

### ISSUE THREAD

**Issue by erg** [AlexIljin/ryu#3]
https://github.com/AlexIljin/ryu/blob/2af4de049d97a5c0e3582bf1ba35df49c14f375a/ryu.factor#L13

Is Factor smart enough to avoid the extra two multiplications?

**Comment by alex-ilin** [comment]
The `\ mul-shift-all disassemble` call shows that it's not so smart, so we better hand-optimize this. Thanks for noticing!
